import Script from "next/script";
import SessionProviderWrapper from "./components/auth/SessionProviderWrapper";
import { ThemeProvider } from "./context/ThemeContext";
import "./styles/globals.css";
// import "bootstrap/dist/css/bootstrap.rtl.min.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <SessionProviderWrapper>
          <ThemeProvider>{children}</ThemeProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
